name: Build and Upload Cross-Platform Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            zip_name: ProtankiProxy_linux_x64.zip

          - os: macos-latest
            runtime: osx-arm64
            zip_name: ProtankiProxy_osx_arm64.zip

          - os: windows-latest
            runtime: win-x64
            zip_name: ProtankiProxy_win_x64.zip

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: Publish app
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true -o publish

    - name: Zip for Unix
      if: runner.os != 'Windows'
      run: |
        cd publish
        zip -r ../${{ matrix.zip_name }} .
      shell: bash

    - name: Zip for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: Compress-Archive -Path publish\* -DestinationPath ${{ matrix.zip_name }}

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.zip_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
